// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";
import type { FunctionDescriptor } from "../../types";

export type HealthCheckGetError = never;

const allowedTags = [] as const;

/**
 * Decodes raw error data to typed HealthCheckGetError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeHealthCheckGetError = (
  e: unknown
): HealthCheckGetError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  return undefined;
};

/**
 * Asserts error is valid HealthCheckGetError.
 * Throws if undeclared error escapes.
 */
export const assertHealthCheckGetError = (
  e: unknown
): asserts e is HealthCheckGetError => {
  if (!decodeHealthCheckGetError(e)) {
    throw new Error("Illegal error thrown by healthCheck/get");
  }
};

const dataSchema = Schema.Unknown;

/**
 * Function descriptor for healthCheck/get.
 * Includes both error decoding and data schema validation.
 */
export const healthCheckGetDescriptor: FunctionDescriptor<
  typeof dataSchema.Type,
  HealthCheckGetError
> = {
  path: "healthCheck/get",
  allowedTags,
  decodeError: decodeHealthCheckGetError,
  dataSchema,
};
