// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import type { ErrorDescriptor } from "../../types";

export type HealthCheckGetError = never;

const allowedTags = [] as const;

/**
 * Decodes raw error data to typed HealthCheckGetError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeHealthCheckGetError = (
  e: unknown
): HealthCheckGetError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  return undefined;
};

/**
 * Asserts error is valid HealthCheckGetError.
 * Throws if undeclared error escapes.
 */
export const assertHealthCheckGetError = (
  e: unknown
): asserts e is HealthCheckGetError => {
  if (!decodeHealthCheckGetError(e)) {
    throw new Error("Illegal error thrown by healthCheck/get");
  }
};

/**
 * Error descriptor for healthCheck/get.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const healthCheckGetDescriptor: ErrorDescriptor<HealthCheckGetError> = {
  path: "healthCheck/get",
  allowedTags,
  decode: decodeHealthCheckGetError,
};
