// AUTO-GENERATED by contract-codegen - DO NOT EDIT
// Function descriptor for typed error contracts and data schema validation.
// Used by generated contracts and the useEffectMutation/useEffectQuery hooks.

import type { GenericId } from "convex/values";
import { Data, Schema, type Schema as SchemaType } from "effect";

/**
 * Error thrown when data schema decoding fails.
 */
export class SchemaDecodeError extends Data.TaggedError("SchemaDecodeError")<{
  readonly path: string;
  readonly cause: unknown;
}> {}

/**
 * Full function descriptor for typed Convex function contracts.
 * Includes both error decoding and data schema validation.
 */
export interface FunctionDescriptor<A, E, I = A> {
  readonly path: string;
  readonly allowedTags: readonly string[];
  readonly decodeError: (e: unknown) => E | undefined;
  readonly dataSchema: SchemaType.Schema<A, I>;
}

/**
 * Creates an Effect Schema for a Convex Id<TableName>.
 * The resulting type is `string & Brand<TableName>` which is
 * structurally compatible with Convex's Id<TableName>.
 */
export const IdSchema = <T extends string>(_table: T) =>
  Schema.String.pipe(
    Schema.filter((s): s is GenericId<T> => typeof s === "string")
  );
