/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as App_rootRouteImport } from './routes/_app/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTodosIndexRouteImport } from './routes/_app/todos/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const App_rootRoute = App_rootRouteImport.update({
  id: '/_app/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodosIndexRoute = AppTodosIndexRouteImport.update({
  id: '/_app/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_app/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/todos': typeof AppTodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/todos': typeof AppTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/__root': typeof App_rootRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/todos/': typeof AppTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/dashboard' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/dashboard' | '/todos'
  id:
    | '__root__'
    | '/_app/__root'
    | '/_app/'
    | '/api/auth/$'
    | '/_app/dashboard/'
    | '/_app/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  App_rootRoute: typeof App_rootRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppTodosIndexRoute: typeof AppTodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/__root': {
      id: '/_app/__root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof App_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/todos/': {
      id: '/_app/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  App_rootRoute: App_rootRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppTodosIndexRoute: AppTodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
