// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";
import type { FunctionDescriptor } from "../../types";

export type PrivateDataGetError = never;

const allowedTags = [] as const;

/**
 * Decodes raw error data to typed PrivateDataGetError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodePrivateDataGetError = (
  e: unknown
): PrivateDataGetError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  return undefined;
};

/**
 * Asserts error is valid PrivateDataGetError.
 * Throws if undeclared error escapes.
 */
export const assertPrivateDataGetError = (
  e: unknown
): asserts e is PrivateDataGetError => {
  if (!decodePrivateDataGetError(e)) {
    throw new Error("Illegal error thrown by privateData/get");
  }
};

const dataSchema = Schema.Unknown;

/**
 * Function descriptor for privateData/get.
 * Includes both error decoding and data schema validation.
 */
export const privateDataGetDescriptor: FunctionDescriptor<
  typeof dataSchema.Type,
  PrivateDataGetError
> = {
  path: "privateData/get",
  allowedTags,
  decodeError: decodePrivateDataGetError,
  dataSchema,
};
