import type { ContractInput, ReturnTypeInfo, TableSchemaDef } from "../types";
import { moduleToPascalCase, toKebabCase } from "../utils";

interface SchemaMapping {
  schemaName: string;
  schemaImport: string | null;
  isArray: boolean;
  isNull: boolean;
}

function mapReturnTypeToSchema(
  returnTypeInfo: ReturnTypeInfo,
  tableSchemas: TableSchemaDef[]
): SchemaMapping {
  if (returnTypeInfo.isNull) {
    return {
      schemaName: "Schema.Null",
      schemaImport: null,
      isArray: false,
      isNull: true,
    };
  }

  if (returnTypeInfo.tableName) {
    const extractedTableName = returnTypeInfo.tableName;
    const schema = tableSchemas.find(
      (t) => t.tableName.toLowerCase() === extractedTableName.toLowerCase()
    );
    if (schema) {
      return {
        schemaName: schema.name,
        schemaImport: toKebabCase(schema.name),
        isArray: returnTypeInfo.isArray,
        isNull: false,
      };
    }
  }

  return {
    schemaName: "Schema.Unknown",
    schemaImport: null,
    isArray: false,
    isNull: false,
  };
}

export function generateFunctionContract(
  input: ContractInput & { returnTypeInfo: ReturnTypeInfo },
  depth: number,
  tableSchemas: TableSchemaDef[]
): string {
  const { modulePath, errors, returnTypeInfo } = input;
  const pascalPrefix = moduleToPascalCase(modulePath);
  const upDirs = "../".repeat(depth + 1);
  const typesImport = `${upDirs}types`;
  const errorsImport = `${upDirs}../convex/schemas/errors`;

  const schemaMapping = mapReturnTypeToSchema(returnTypeInfo, tableSchemas);

  const lines: string[] = [
    "// AUTO-GENERATED by contract-codegen - DO NOT EDIT",
    "",
  ];

  lines.push(`import type { FunctionDescriptor } from "${typesImport}";`);
  lines.push(`import { Schema } from "effect";`);

  if (errors.length > 0) {
    const errorTags = [...new Set(errors.map((e) => e.tag))].sort();
    lines.push(`import { ${errorTags.join(", ")} } from "${errorsImport}";`);
  }

  if (schemaMapping.schemaImport) {
    const schemaPath = `${upDirs}schemas/${schemaMapping.schemaImport}`;
    lines.push(`import { ${schemaMapping.schemaName} } from "${schemaPath}";`);
  }

  lines.push("");

  if (errors.length === 0) {
    lines.push(`export type ${pascalPrefix}Error = never;`);
  } else {
    lines.push(`export type ${pascalPrefix}Error =`);
    for (const err of errors) {
      lines.push(`  | ${err.tag}`);
    }
    lines[lines.length - 1] += ";";
  }

  lines.push("");
  const tagsList = errors.map((e) => `"${e.tag}"`).join(", ");
  lines.push(`const allowedTags = [${tagsList}] as const;`);
  lines.push("");

  lines.push("/**");
  lines.push(` * Decodes raw error data to typed ${pascalPrefix}Error.`);
  lines.push(" * Returns undefined if error tag not in allowed set.");
  lines.push(" */");
  lines.push(`export const decode${pascalPrefix}Error = (`);
  lines.push("  e: unknown");
  lines.push(`): ${pascalPrefix}Error | undefined => {`);
  lines.push(`  if (typeof e !== "object" || e === null || !("_tag" in e)) {`);
  lines.push("    return undefined;");
  lines.push("  }");

  if (errors.length === 0) {
    lines.push("  return undefined;");
  } else {
    lines.push("  const err = e as");
    for (const err of errors) {
      const prefix = "    |";
      if (err.fields.length === 0) {
        lines.push(`${prefix} { _tag: "${err.tag}" }`);
      } else {
        const fields = err.fields
          .map((f) => `${f.name}${f.optional ? "?" : ""}: ${f.type}`)
          .join("; ");
        lines.push(`${prefix} { _tag: "${err.tag}"; ${fields} }`);
      }
    }
    lines[lines.length - 1] += ";";
    lines.push("");
    lines.push("  switch (err._tag) {");
    for (const err of errors) {
      lines.push(`    case "${err.tag}":`);
      lines.push(`      return new ${err.tag}(err);`);
    }
    lines.push("    default:");
    lines.push("      return undefined;");
    lines.push("  }");
  }
  lines.push("};");
  lines.push("");

  lines.push("/**");
  lines.push(` * Asserts error is valid ${pascalPrefix}Error.`);
  lines.push(" * Throws if undeclared error escapes.");
  lines.push(" */");
  lines.push(`export const assert${pascalPrefix}Error = (`);
  lines.push("  e: unknown");
  lines.push(`): asserts e is ${pascalPrefix}Error => {`);
  lines.push(`  if (!decode${pascalPrefix}Error(e)) {`);
  lines.push(`    throw new Error('Illegal error thrown by ${modulePath}');`);
  lines.push("  }");
  lines.push("};");
  lines.push("");

  let dataSchemaExpr: string;
  if (schemaMapping.isNull) {
    dataSchemaExpr = "Schema.Null";
  } else if (schemaMapping.isArray) {
    dataSchemaExpr = `Schema.Array(${schemaMapping.schemaName})`;
  } else {
    dataSchemaExpr = schemaMapping.schemaName;
  }

  lines.push(`const dataSchema = ${dataSchemaExpr};`);
  lines.push("");

  const camelDescriptorName =
    pascalPrefix.charAt(0).toLowerCase() + pascalPrefix.slice(1);
  lines.push("/**");
  lines.push(` * Function descriptor for ${modulePath}.`);
  lines.push(" * Includes both error decoding and data schema validation.");
  lines.push(" */");
  lines.push(
    `export const ${camelDescriptorName}Descriptor: FunctionDescriptor<`
  );
  lines.push("  typeof dataSchema.Type,");
  lines.push(`  ${pascalPrefix}Error,`);
  lines.push("  typeof dataSchema.Encoded");
  lines.push("> = {");
  lines.push(`  path: "${modulePath}",`);
  lines.push("  allowedTags,");
  lines.push(`  decodeError: decode${pascalPrefix}Error,`);
  lines.push("  dataSchema,");
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}
