import type { ConvexFieldDef, TableSchemaDef } from "../types";

const CONVEX_TO_EFFECT_MAP: Record<string, string> = {
  "v.string()": "Schema.String",
  "v.boolean()": "Schema.Boolean",
  "v.number()": "Schema.Number",
  "v.int64()": "Schema.BigInt",
  "v.float64()": "Schema.Number",
  "v.bytes()": "Schema.Uint8ArrayFromSelf",
  "v.null()": "Schema.Null",
  "v.any()": "Schema.Unknown",
};

const V_OPTIONAL_REGEX = /^v\.optional\((.+)\)$/;
const V_ARRAY_REGEX = /^v\.array\((.+)\)$/;
const V_UNION_REGEX = /^v\.union\((.+)\)$/;
const V_ID_REGEX = /^v\.id\(["'](\w+)["']\)$/;
const V_LITERAL_REGEX = /^v\.literal\((.+)\)$/;

function parseUnionArgs(argsStr: string): string[] {
  const results: string[] = [];
  let depth = 0;
  let current = "";
  for (const char of argsStr) {
    if (char === "(" || char === "[" || char === "{") {
      depth++;
      current += char;
    } else if (char === ")" || char === "]" || char === "}") {
      depth--;
      current += char;
    } else if (char === "," && depth === 0) {
      results.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  if (current.trim()) {
    results.push(current.trim());
  }
  return results;
}

export function convexTypeToEffectSchema(convexType: string): string {
  const optionalMatch = convexType.match(V_OPTIONAL_REGEX);
  if (optionalMatch) {
    const inner = convexTypeToEffectSchema(optionalMatch[1]!);
    return `Schema.optional(${inner})`;
  }
  const arrayMatch = convexType.match(V_ARRAY_REGEX);
  if (arrayMatch) {
    const inner = convexTypeToEffectSchema(arrayMatch[1]!);
    return `Schema.Array(${inner})`;
  }
  const unionMatch = convexType.match(V_UNION_REGEX);
  if (unionMatch) {
    const innerTypes = parseUnionArgs(unionMatch[1]!);
    const mapped = innerTypes.map(convexTypeToEffectSchema);
    return `Schema.Union(${mapped.join(", ")})`;
  }
  const idMatch = convexType.match(V_ID_REGEX);
  if (idMatch) {
    return `IdSchema("${idMatch[1]!}")`;  
  }
  const literalMatch = convexType.match(V_LITERAL_REGEX);
  if (literalMatch) {
    return `Schema.Literal(${literalMatch[1]})`;
  }
  return CONVEX_TO_EFFECT_MAP[convexType] ?? "Schema.Unknown";
}

export function generateDataSchema(table: TableSchemaDef): string {
  const lines: string[] = [
    "// AUTO-GENERATED by contract-codegen - DO NOT EDIT",
    "",
    'import { Schema } from "effect";',
    'import { IdSchema } from "../types";',
    "",
  ];

  lines.push(`export const ${table.name}Base = Schema.Struct({`);
  for (const field of table.fields) {
    const effectType = convexTypeToEffectSchema(field.type);
    lines.push(`  ${field.name}: ${effectType},`);
  }
  lines.push("});");
  lines.push("");

  lines.push(`export const ${table.name} = Schema.Struct({`);
  lines.push(`  _id: IdSchema("${table.tableName}"),`);
  lines.push("  _creationTime: Schema.Number,");
  for (const field of table.fields) {
    const effectType = convexTypeToEffectSchema(field.type);
    lines.push(`  ${field.name}: ${effectType},`);
  }
  lines.push("});");
  lines.push("");

  lines.push(`export type ${table.name}Base = typeof ${table.name}Base.Type;`);
  lines.push(`export type ${table.name} = typeof ${table.name}.Type;`);
  lines.push("");

  return lines.join("\n");
}
