import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { Project } from "ts-morph";
import { extractAllErrorFields } from "./parser/errors";
import { scanConvexFile } from "./parser/functions";
import { extractTableSchemas } from "./parser/schemas";
import { generateDataSchema } from "./generator/schemas";
import { generateFunctionContract } from "./generator/contracts";
import { toKebabCase } from "./utils";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TS_EXT_REGEX = /\.ts$/;
const BACKSLASH_REGEX = /\\/g;

function shouldSkipFile(name: string): boolean {
  if (!name.endsWith(".ts")) return true;
  if (name === "convex.config.ts") return true;
  if (name === "schema.ts") return true;
  if (name === "http.ts") return true;
  if (name.includes(".config.")) return true;
  return false;
}

function shouldSkipDir(name: string): boolean {
  return (
    name.startsWith("_") ||
    name === "lib" ||
    name === "schemas" ||
    name === "contracts"
  );
}

function findConvexFiles(
  dir: string,
  basePath = ""
): { path: string; modulePath: string }[] {
  const results: { path: string; modulePath: string }[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (shouldSkipDir(entry.name)) {
        continue;
      }
      const subModulePath = basePath ? `${basePath}.${entry.name}` : entry.name;
      results.push(...findConvexFiles(fullPath, subModulePath));
      continue;
    }

    if (shouldSkipFile(entry.name)) {
      continue;
    }

    const moduleName = path.basename(entry.name, ".ts");
    const modulePath = basePath ? `${basePath}.${moduleName}` : moduleName;

    results.push({ path: fullPath, modulePath });
  }

  return results;
}

export function main() {
  const convexDir = path.resolve(__dirname, "../../src/convex");
  const errorsFile = path.join(convexDir, "schemas/errors.ts");
  const schemaFile = path.join(convexDir, "schema.ts");
  const contractsDir = path.join(__dirname, "../../src/contracts");
  const errorsOutputDir = path.join(contractsDir, "errors");
  const schemasOutputDir = path.join(contractsDir, "schemas");
  const tsconfigPath = path.join(convexDir, "tsconfig.json");

  console.log("Scanning Convex functions for function contracts...\n");

  const project = new Project({
    tsConfigFilePath: tsconfigPath,
    skipAddingFilesFromTsConfig: true,
  });

  const errorFields = extractAllErrorFields(project, errorsFile);
  const tableSchemas = extractTableSchemas(project, schemaFile);

  if (fs.existsSync(schemasOutputDir)) {
    fs.rmSync(schemasOutputDir, { recursive: true });
  }
  fs.mkdirSync(schemasOutputDir, { recursive: true });

  const generatedSchemas: string[] = [];

  for (const table of tableSchemas) {
    const code = generateDataSchema(table);
    const fileName = `${toKebabCase(table.name)}.ts`;
    const outFile = path.join(schemasOutputDir, fileName);
    fs.writeFileSync(outFile, code);
    generatedSchemas.push(fileName);
  }

  const files = findConvexFiles(convexDir);
  for (const { path: filePath } of files) {
    project.addSourceFileAtPath(filePath);
  }

  if (fs.existsSync(errorsOutputDir)) {
    fs.rmSync(errorsOutputDir, { recursive: true });
  }
  fs.mkdirSync(errorsOutputDir, { recursive: true });

  const generated: string[] = [];

  for (const { path: filePath, modulePath } of files) {
    const scanned = scanConvexFile(project, filePath, errorFields);
    if (!scanned) continue;

    for (const fn of scanned.functions) {
      const errors = fn.errorTags.map((tag: string) => ({
        tag,
        fields: errorFields[tag] ?? [],
      }));

      const fullModulePath = `${modulePath}/${fn.functionName}`;
      const depth = modulePath.split(".").length;

      const code = generateFunctionContract(
        {
          functionName: fn.functionName,
          modulePath: fullModulePath,
          errors,
          returnTypeInfo: fn.returnTypeInfo,
        },
        depth,
        tableSchemas
      );

      const outDir = path.join(errorsOutputDir, modulePath);
      fs.mkdirSync(outDir, { recursive: true });

      const kebabFnName = toKebabCase(fn.functionName);
      const outFile = path.join(outDir, `${kebabFnName}.ts`);
      fs.writeFileSync(outFile, code);

      const relativeToOutput = path.relative(errorsOutputDir, outFile);
      generated.push(relativeToOutput);
    }
  }

  const mainIndexLines = [
    "// AUTO-GENERATED by contract-codegen - DO NOT EDIT",
    "// biome-ignore-all lint/performance/noBarrelFile: intentional for generated API",
    'export * from "./types";',
  ];

  for (const file of generated) {
    const importPath = `./errors/${file.replace(TS_EXT_REGEX, "").replace(BACKSLASH_REGEX, "/")}`;
    mainIndexLines.push(`export * from "${importPath}";`);
  }

  for (const file of generatedSchemas) {
    const importPath = `./schemas/${file.replace(TS_EXT_REGEX, "")}`;
    mainIndexLines.push(`export * from "${importPath}";`);
  }

  fs.writeFileSync(
    path.join(contractsDir, "index.ts"),
    mainIndexLines.join("\n")
  );

  const typesTsContent = `// AUTO-GENERATED by contract-codegen - DO NOT EDIT
// Function descriptor for typed error contracts and data schema validation.
// Used by generated contracts and the useEffectMutation/useEffectQuery hooks.

import { Data, Schema, type Schema as SchemaType } from "effect";
import type { GenericId } from "convex/values";

/**
 * Error thrown when data schema decoding fails.
 */
export class SchemaDecodeError extends Data.TaggedError("SchemaDecodeError")<{
  readonly path: string;
  readonly cause: unknown;
}> {}

/**
 * Full function descriptor for typed Convex function contracts.
 * Includes both error decoding and data schema validation.
 */
export interface FunctionDescriptor<A, E, I = A> {
  readonly path: string;
  readonly allowedTags: readonly string[];
  readonly decodeError: (e: unknown) => E | undefined;
  readonly dataSchema: SchemaType.Schema<A, I>;
}

/**
 * Creates an Effect Schema for a Convex Id<TableName>.
 * The resulting type is \`string & Brand<TableName>\` which is
 * structurally compatible with Convex's Id<TableName>.
 */
export const IdSchema = <T extends string>(_table: T) =>
  Schema.String.pipe(Schema.filter((s): s is GenericId<T> => typeof s === "string"));
`
  fs.writeFileSync(path.join(contractsDir, "types.ts"), typesTsContent);


  console.log("\nFormatting generated files...");
  try {
    const rootDir = path.resolve(__dirname, "../../../..");
    const relativeContractsDir = path.relative(rootDir, contractsDir);

    execSync(`pnpm dlx ultracite fix "${relativeContractsDir}"`, {
      stdio: "inherit",
      cwd: rootDir,
    });
    console.log("Formatting complete.");
  } catch (error) {
    console.error("Failed to format generated files:", error);
  }
}
