// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { UnknownError } from "@/convex/schemas/errors";

export type UserProfilesGetCurrentProfileError = UnknownError;

const allowedTags = ["UnknownError"] as const;

/**
 * Decodes raw error data to typed UserProfilesGetCurrentProfileError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeUserProfilesGetCurrentProfileError = (
  e: unknown
): UserProfilesGetCurrentProfileError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid UserProfilesGetCurrentProfileError.
 * Throws if undeclared error escapes.
 */
export const assertUserProfilesGetCurrentProfileError = (
  e: unknown
): asserts e is UserProfilesGetCurrentProfileError => {
  if (!decodeUserProfilesGetCurrentProfileError(e)) {
    throw new Error("Illegal error thrown by userProfiles/getCurrentProfile");
  }
};

/**
 * Error descriptor for userProfiles/getCurrentProfile.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const userProfilesGetCurrentProfileDescriptor = {
  path: "userProfiles/getCurrentProfile" as const,
  allowedTags,
  decode: decodeUserProfilesGetCurrentProfileError,
} as const;
