// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";

export const TodoBase = Schema.Struct({
  text: Schema.String,
  completed: Schema.Boolean,
});

export const Todo = Schema.Struct({
  _id: Schema.String,
  _creationTime: Schema.Number,
  text: Schema.String,
  completed: Schema.Boolean,
});

export type TodoBase = typeof TodoBase.Type;
export type Todo = typeof Todo.Type;
