// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";

export const UserProfileId = Schema.String.pipe(Schema.brand("UserProfileId"));
export type UserProfileId = typeof UserProfileId.Type;

export const UserProfileBase = Schema.Struct({
  userId: Schema.String,
  name: Schema.optional(Schema.String),
  avatar: Schema.optional(Schema.String),
});

export const UserProfile = Schema.Struct({
  _id: UserProfileId,
  _creationTime: Schema.Number,
  userId: Schema.String,
  name: Schema.optional(Schema.String),
  avatar: Schema.optional(Schema.String),
});

export type UserProfileBase = typeof UserProfileBase.Type;
export type UserProfile = typeof UserProfile.Type;
