// AUTO-GENERATED by contract-codegen - DO NOT EDIT

export type PrivateDataGetError = never;

const allowedTags = [] as const;

/**
 * Decodes raw error data to typed PrivateDataGetError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodePrivateDataGetError = (
  e: unknown
): PrivateDataGetError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  return undefined;
};

/**
 * Asserts error is valid PrivateDataGetError.
 * Throws if undeclared error escapes.
 */
export const assertPrivateDataGetError = (
  e: unknown
): asserts e is PrivateDataGetError => {
  if (!decodePrivateDataGetError(e)) {
    throw new Error("Illegal error thrown by privateData/get");
  }
};

/**
 * Error descriptor for privateData/get.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const privateDataGetDescriptor = {
  path: "privateData/get" as const,
  allowedTags,
  decode: decodePrivateDataGetError,
} as const;
