// packages/backend/scripts/effect-codegen.ts
// biome-ignore lint/performance/noNamespaceImport: node:fs requires namespace
import * as fs from "node:fs";
// biome-ignore lint/performance/noNamespaceImport: node:path requires namespace
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

interface ErrorFieldDef {
  name: string;
  type: string;
  optional: boolean;
}

interface ErrorDef {
  tag: string;
  fields: ErrorFieldDef[];
}

interface ScannedFunction {
  functionName: string;
  errorTags: string[];
}

interface ContractInput {
  functionName: string;
  modulePath: string;
  errors: ErrorDef[];
}

// -----------------------------------------------------------------------------
// Error field definitions (from @repo/shared/errors)
// -----------------------------------------------------------------------------

const ERROR_FIELDS: Record<string, ErrorFieldDef[]> = {
  UnauthenticatedError: [],
  NotAuthorizedError: [{ name: "resource", type: "string", optional: false }],
  NotFoundError: [
    { name: "id", type: "string", optional: true },
    { name: "handle", type: "string", optional: true },
  ],
  ForbiddenError: [{ name: "message", type: "string", optional: true }],
  UnknownError: [{ name: "message", type: "string", optional: false }],
  InvalidCtxError: [],
  GetUserIdentityError: [{ name: "message", type: "string", optional: false }],
};

// -----------------------------------------------------------------------------
// Scanner - Regex patterns at top level for performance
// -----------------------------------------------------------------------------

const ERRORS_EXPORT_REGEX =
  /export\s+const\s+errors\s*=\s*\[([^\]]*)\]\s*as\s+const/;
const FUNCTION_EXPORT_REGEX =
  /export\s+const\s+(\w+)\s*=\s*(?:query|mutation|action)\s*\(/;
const TS_EXT_REGEX = /\.ts$/;
const BACKSLASH_REGEX = /\\/g;

/**
 * Scans Convex file content for error exports.
 * Looks for: export const errors = [Error1, Error2] as const;
 */
export function scanConvexFile(content: string): ScannedFunction | null {
  const match = ERRORS_EXPORT_REGEX.exec(content);

  if (!match) {
    return null;
  }

  const errorList = match[1] ?? "";
  const errorTags = errorList
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  // Extract function name from the file (query/mutation export)
  const fnMatch = FUNCTION_EXPORT_REGEX.exec(content);
  const functionName = fnMatch?.[1] ?? "unknown";

  return { functionName, errorTags };
}

// -----------------------------------------------------------------------------
// Generator
// -----------------------------------------------------------------------------

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Generates error contract code for a Convex function.
 */
export function generateErrorContract(input: ContractInput): string {
  const { functionName, modulePath, errors } = input;
  const pascalName = capitalize(functionName);

  const lines: string[] = [
    "// AUTO-GENERATED by effect-codegen - DO NOT EDIT",
    "",
  ];

  // Generate union type
  if (errors.length === 0) {
    lines.push(`export type ${pascalName}Error = never;`);
  } else {
    lines.push(`export type ${pascalName}Error =`);
    for (const err of errors) {
      if (err.fields.length === 0) {
        lines.push(`  | { _tag: "${err.tag}" }`);
      } else {
        const fields = err.fields
          .map((f) => `${f.name}${f.optional ? "?" : ""}: ${f.type}`)
          .join("; ");
        lines.push(`  | { _tag: "${err.tag}"; ${fields} }`);
      }
    }
    lines[lines.length - 1] += ";";
  }

  lines.push("");

  // Generate allowedTags
  const tagsList = errors.map((e) => `"${e.tag}"`).join(", ");
  lines.push(`const allowedTags = [${tagsList}] as const;`);
  lines.push("");

  // Generate decode function
  lines.push("/**");
  lines.push(` * Decodes raw error data to typed ${pascalName}Error.`);
  lines.push(" * Returns undefined if error tag not in allowed set.");
  lines.push(" */");
  lines.push(`export const decode${pascalName}Error = (`);
  lines.push("  e: unknown");
  lines.push(`): ${pascalName}Error | undefined =>`);
  lines.push(`  typeof e === "object" &&`);
  lines.push("  e !== null &&");
  lines.push(`  "_tag" in e &&`);
  lines.push(
    "  allowedTags.includes((e as { _tag: string })._tag as (typeof allowedTags)[number])"
  );
  lines.push(`    ? (e as ${pascalName}Error)`);
  lines.push("    : undefined;");
  lines.push("");

  // Generate assert function
  lines.push("/**");
  lines.push(` * Asserts error is valid ${pascalName}Error.`);
  lines.push(" * Throws if undeclared error escapes.");
  lines.push(" */");
  lines.push(`export const assert${pascalName}Error = (`);
  lines.push("  e: unknown");
  lines.push(`): asserts e is ${pascalName}Error => {`);
  lines.push(`  if (!decode${pascalName}Error(e)) {`);
  lines.push(`    throw new Error(\`Illegal error thrown by ${modulePath}\`);`);
  lines.push("  }");
  lines.push("};");
  lines.push("");

  // Generate descriptor
  lines.push("/**");
  lines.push(` * Error descriptor for ${modulePath}.`);
  lines.push(" * Pass to useEffectMutation/useEffectQuery for typed errors.");
  lines.push(" */");
  lines.push(`export const ${functionName}Descriptor = {`);
  lines.push(`  path: "${modulePath}" as const,`);
  lines.push("  allowedTags,");
  lines.push(`  decode: decode${pascalName}Error,`);
  lines.push("} as const;");
  lines.push("");

  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// CLI Runner
// -----------------------------------------------------------------------------

/** Checks if file should be skipped */
function shouldSkipFile(name: string): boolean {
  if (!name.endsWith(".ts")) {
    return true;
  }
  if (name === "convex.config.ts") {
    return true;
  }
  if (name === "schema.ts") {
    return true;
  }
  if (name === "http.ts") {
    return true;
  }
  if (name.includes(".config.")) {
    return true;
  }
  return false;
}

/** Checks if directory should be skipped */
function shouldSkipDir(name: string): boolean {
  return name.startsWith("_") || name === "lib" || name === "schemas";
}

function findConvexFiles(
  dir: string,
  basePath = ""
): { path: string; modulePath: string }[] {
  const results: { path: string; modulePath: string }[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (shouldSkipDir(entry.name)) {
        continue;
      }
      const subModulePath = basePath ? `${basePath}.${entry.name}` : entry.name;
      results.push(...findConvexFiles(fullPath, subModulePath));
      continue;
    }

    if (shouldSkipFile(entry.name)) {
      continue;
    }

    const moduleName = path.basename(entry.name, ".ts");
    const modulePath = basePath ? `${basePath}.${moduleName}` : moduleName;

    results.push({ path: fullPath, modulePath });
  }

  return results;
}

function main() {
  const convexDir = path.resolve(__dirname, "../convex");
  // Note: Using lib/effect-contracts instead of _generated/effect
  // because Convex dev process manages _generated and would delete our files
  const outputDir = path.join(convexDir, "lib/effect-contracts");

  console.log("Scanning Convex functions for error contracts...\n");

  // Clean output directory
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true });
  }
  fs.mkdirSync(outputDir, { recursive: true });

  const files = findConvexFiles(convexDir);
  const generated: string[] = [];

  for (const { path: filePath, modulePath } of files) {
    const content = fs.readFileSync(filePath, "utf-8");
    const scanned = scanConvexFile(content);

    if (!scanned) {
      continue;
    }

    // Build error definitions
    const errors: ErrorDef[] = scanned.errorTags.map((tag) => ({
      tag,
      fields: ERROR_FIELDS[tag] ?? [],
    }));

    const code = generateErrorContract({
      functionName: scanned.functionName,
      modulePath,
      errors,
    });

    // Create output path mirroring module structure
    const outDir = path.join(outputDir, ...modulePath.split(".").slice(0, -1));
    fs.mkdirSync(outDir, { recursive: true });

    const outFile = path.join(outDir, `${scanned.functionName}.ts`);
    fs.writeFileSync(outFile, code);

    const relativeToConvex = path.relative(convexDir, outFile);
    const relativeToOutput = path.relative(outputDir, outFile);
    console.log(`  Generated: ${relativeToConvex}`);
    generated.push(relativeToOutput);
  }

  // Generate index file (barrel file intentional for generated contracts)
  const indexLines = ["// AUTO-GENERATED by effect-codegen - DO NOT EDIT", ""];

  if (generated.length > 0) {
    indexLines.push(
      "// biome-ignore lint/performance/noBarrelFile: intentional for generated API"
    );
  }

  for (const file of generated) {
    const importPath = `./${file.replace(TS_EXT_REGEX, "").replace(BACKSLASH_REGEX, "/")}`;
    indexLines.push(`export * from "${importPath}";`);
  }
  indexLines.push("");

  fs.writeFileSync(path.join(outputDir, "index.ts"), indexLines.join("\n"));
  console.log("\n  Generated: lib/effect-contracts/index.ts");

  console.log(`\nDone! Generated ${generated.length} error contracts.`);
}

main();
