// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";
import { ForbiddenError, UnknownError } from "../../../convex/schemas/errors";
import type { FunctionDescriptor } from "../../types";

export type TodosCreateError = ForbiddenError | UnknownError;

const allowedTags = ["ForbiddenError", "UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosCreateError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosCreateError = (
  e: unknown
): TodosCreateError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as
    | { _tag: "ForbiddenError"; message?: string }
    | { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "ForbiddenError":
      return new ForbiddenError(err);
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosCreateError.
 * Throws if undeclared error escapes.
 */
export const assertTodosCreateError = (
  e: unknown
): asserts e is TodosCreateError => {
  if (!decodeTodosCreateError(e)) {
    throw new Error("Illegal error thrown by todos/create");
  }
};

const dataSchema = Schema.Unknown;

/**
 * Function descriptor for todos/create.
 * Includes both error decoding and data schema validation.
 */
export const todosCreateDescriptor: FunctionDescriptor<
  typeof dataSchema.Type,
  TodosCreateError,
  typeof dataSchema.Encoded
> = {
  path: "todos/create",
  allowedTags,
  decodeError: decodeTodosCreateError,
  dataSchema,
};
