// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { ForbiddenError, UnknownError } from "../../../convex/schemas/errors";
import type { ErrorDescriptor } from "../../types";

export type TodosCreateError = ForbiddenError | UnknownError;

const allowedTags = ["ForbiddenError", "UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosCreateError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosCreateError = (
  e: unknown
): TodosCreateError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as
    | { _tag: "ForbiddenError"; message?: string }
    | { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "ForbiddenError":
      return new ForbiddenError(err);
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosCreateError.
 * Throws if undeclared error escapes.
 */
export const assertTodosCreateError = (
  e: unknown
): asserts e is TodosCreateError => {
  if (!decodeTodosCreateError(e)) {
    throw new Error("Illegal error thrown by todos/create");
  }
};

/**
 * Error descriptor for todos/create.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const todosCreateDescriptor: ErrorDescriptor<TodosCreateError> = {
  path: "todos/create",
  allowedTags,
  decode: decodeTodosCreateError,
};
