// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { ForbiddenError, UnknownError } from "../../../convex/schemas/errors";
import type { ErrorDescriptor } from "../../types";

export type TodosDeleteTodoError = ForbiddenError | UnknownError;

const allowedTags = ["ForbiddenError", "UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosDeleteTodoError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosDeleteTodoError = (
  e: unknown
): TodosDeleteTodoError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as
    | { _tag: "ForbiddenError"; message?: string }
    | { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "ForbiddenError":
      return new ForbiddenError(err);
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosDeleteTodoError.
 * Throws if undeclared error escapes.
 */
export const assertTodosDeleteTodoError = (
  e: unknown
): asserts e is TodosDeleteTodoError => {
  if (!decodeTodosDeleteTodoError(e)) {
    throw new Error("Illegal error thrown by todos/deleteTodo");
  }
};

/**
 * Error descriptor for todos/deleteTodo.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const todosDeleteTodoDescriptor: ErrorDescriptor<TodosDeleteTodoError> =
  {
    path: "todos/deleteTodo",
    allowedTags,
    decode: decodeTodosDeleteTodoError,
  };
