// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { Schema } from "effect";
import { UnknownError } from "../../../convex/schemas/errors";
import { Todo } from "../../schemas/todo";
import type { FunctionDescriptor } from "../../types";

export type TodosGetAllError = UnknownError;

const allowedTags = ["UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosGetAllError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosGetAllError = (
  e: unknown
): TodosGetAllError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosGetAllError.
 * Throws if undeclared error escapes.
 */
export const assertTodosGetAllError = (
  e: unknown
): asserts e is TodosGetAllError => {
  if (!decodeTodosGetAllError(e)) {
    throw new Error("Illegal error thrown by todos/getAll");
  }
};

const dataSchema = Schema.Array(Todo);

/**
 * Function descriptor for todos/getAll.
 * Includes both error decoding and data schema validation.
 */
export const todosGetAllDescriptor: FunctionDescriptor<
  typeof dataSchema.Type,
  TodosGetAllError,
  typeof dataSchema.Encoded
> = {
  path: "todos/getAll",
  allowedTags,
  decodeError: decodeTodosGetAllError,
  dataSchema,
};
