// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { ForbiddenError, UnknownError } from "../../../convex/schemas/errors";
import type { ErrorDescriptor } from "../../types";

export type TodosToggleError = ForbiddenError | UnknownError;

const allowedTags = ["ForbiddenError", "UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosToggleError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosToggleError = (
  e: unknown
): TodosToggleError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as
    | { _tag: "ForbiddenError"; message?: string }
    | { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "ForbiddenError":
      return new ForbiddenError(err);
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosToggleError.
 * Throws if undeclared error escapes.
 */
export const assertTodosToggleError = (
  e: unknown
): asserts e is TodosToggleError => {
  if (!decodeTodosToggleError(e)) {
    throw new Error("Illegal error thrown by todos/toggle");
  }
};

/**
 * Error descriptor for todos/toggle.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const todosToggleDescriptor: ErrorDescriptor<TodosToggleError> = {
  path: "todos/toggle",
  allowedTags,
  decode: decodeTodosToggleError,
};
