// AUTO-GENERATED by contract-codegen - DO NOT EDIT

import { UnknownError } from "@/convex/schemas/errors";

export type TodosGetAllError = UnknownError;

const allowedTags = ["UnknownError"] as const;

/**
 * Decodes raw error data to typed TodosGetAllError.
 * Returns undefined if error tag not in allowed set.
 */
export const decodeTodosGetAllError = (
  e: unknown
): TodosGetAllError | undefined => {
  if (typeof e !== "object" || e === null || !("_tag" in e)) {
    return undefined;
  }
  const err = e as { _tag: "UnknownError"; message: string };

  switch (err._tag) {
    case "UnknownError":
      return new UnknownError(err);
    default:
      return undefined;
  }
};

/**
 * Asserts error is valid TodosGetAllError.
 * Throws if undeclared error escapes.
 */
export const assertTodosGetAllError = (
  e: unknown
): asserts e is TodosGetAllError => {
  if (!decodeTodosGetAllError(e)) {
    throw new Error("Illegal error thrown by todos/getAll");
  }
};

/**
 * Error descriptor for todos/getAll.
 * Pass to useEffectMutation/useEffectQuery for typed errors.
 */
export const todosGetAllDescriptor = {
  path: "todos/getAll" as const,
  allowedTags,
  decode: decodeTodosGetAllError,
} as const;
